Repository atlp-rwanda/cod-fe, pull requests merged in 2022-06, with the labels that each got.

#14 view-edit-profile-#181414564
  .babelrc
  .eslintrc.json
  jest.config.json
  package.json
  src/api/profileApi.js
  src/api/refreshTokenApi.js
  src/components/Auth/Login.js
  src/components/Auth/Signup.js
  src/components/Header/DashboardHeader.js
  src/components/SideBar/MenuList.js
  src/components/buttons/Button.js
  src/components/profile/Profile.js
  src/components/tables/ApprovalComponent.js
  src/redux/actions/profile.action.js
  src/redux/features/profile.feature.js
  src/redux/reducers.js
  src/routes/index.js
  src/stories/Button.stories.jsx
  src/styles/custom.scss
  src/styles/index.scss
  src/views/profile/ProfileView.js
  tailwind.config.js
  test/integration/dashboardHeaders.test.js
  test/profile.test.js
  test/root.test.js
  webpack.config.js
  yarn.lock
Labels: Ready

#18 feat (Reject trip request) #181414569
  package.json
  src/.DS_Store
  src/api/tripApi.js
  src/api/tripReqApi.js
  src/components/ProfileModal.js
  src/components/tables/ApprovalComponent.js
  src/components/tables/shared/Row.js
  src/components/tables/shared/reqActions.js
  src/index.html
  src/styles/index.scss
  test/integration/tripApprove.test.js
  test/mocks/handlers/approve.handler.js
Labels: Under Review

#20 ft edit trip request with open status #181414570
  package.json
  src/api/accomodationApi.js
  src/api/index.js
  src/api/tripApi.js
  src/api/userApi.js
  src/components/tables/ApprovalComponent.js
  src/components/tables/shared/MoreOptions.js
  src/components/tables/shared/reqActions.js
  src/components/tables/shared/reqColumns.js
  src/components/tripRequest/EditButton.js
  src/components/tripRequest/EditInput.js
  src/components/tripRequest/EditRequest.js
  src/constants/reqColumns.js
  src/redux/actions/editTrip.action.js
  src/redux/features/editTrip.feature.js
  src/redux/reducers.js
  src/routes/index.js
  src/styles/index.scss
  src/views/pages/EditRequestView.js
  tailwind.config.js
  test/integration/editTripRequest.test.js
  test/integration/tripReqTable.test.js
  test/mocks/handlers/auth.handler.js
  test/mocks/handlers/editTrip.handler.js
  test/mocks/handlers/index.js
  yarn.lock
Labels: Ready

#21 feat: user able to search [Delivers #181414575]
  jest.config.json
  src/api/index.js
  src/api/searchApi.js
  src/api/tripReqApi.js
  src/components/Header/DashboardHeader.js
  src/components/Header/TripsHeader.js
  src/components/SideBar/MobileMenu.js
  src/components/SideBar/index.js
  src/components/Trips.js
  src/components/tables/TripRequests.js
  src/components/tables/shared/Header.js
  src/components/tables/shared/SearchOptions.js
  src/redux/features/search.feature.js
  src/redux/reducers.js
  src/redux/thunks/search.js
  src/redux/views/pages.js
  src/styles/DemoSassCss.css
  src/styles/DemoSassCss.css.map
  src/styles/app.css
  src/styles/custom.css
  src/styles/custom.css.map
  src/styles/index.scss
  src/styles/tailwind.css
  src/views/pages/HomeUserView.js
  test/integration/dashboardHeaders.test.js
  test/integration/tripReqTable.test.js
  test/mocks/handlers/index.js
  test/mocks/handlers/search.handler.js
  test/mocks/handlers/tripReq.handler.js
Labels: Under Review

#19 Ft-User Role Settings UI #181414566
  .circleci/config.yml
  .env.example
  .github/workflows/react.js.yml
  cypress/integration/Landing Page/landingPage.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  src/api/accomodationApi.js
  src/api/dummy.js
  src/api/index.js
  src/api/profileApi.js
  src/api/refreshTokenApi.js
  src/api/searchApi.js
  src/api/tripApi.js
  src/api/tripReqApi.js
  src/api/userApi.js
  src/api/userRoleApi.js
  src/components/SideBar/MenuList.js
  src/components/reusable/SearchBar.js
  src/components/superAdmin/UserRoleDashboard.js
  src/components/superAdmin/UserRoles.js
  src/redux/features/userRole.feauture.js
  src/redux/reducers.js
  src/styles/index.scss
  src/views/pages/HomeUserView.js
  test/auth.test.js
  test/integration/userRole.test.js
  test/jest.setup.js
  test/landingPage.test.js
  test/mocks/handlers/approve.handler.js
  test/mocks/handlers/auth.handler.js
  test/mocks/handlers/editTrip.handler.js
  test/mocks/handlers/reset.handler.js
  test/mocks/handlers/search.handler.js
  test/mocks/handlers/tripReq.handler.js
  test/passwordReset.test.js
  test/profile.test.js
  test/root.test.js
  webpack.config.js
  yarn.lock
Labels: Under Review

#26 Fix - (User-Role-Settings)
  src/api/accomodationApi.js
  src/api/index.js
  src/api/profileApi.js
  src/api/refreshTokenApi.js
  src/api/searchApi.js
  src/api/tripApi.js
  src/api/tripReqApi.js
  src/api/userApi.js
  src/api/userRoleApi.js
  src/components/Header/DashboardHeader.js
  src/redux/features/userRole.feauture.js
  test/mocks/handlers/approve.handler.js
  test/mocks/handlers/auth.handler.js
  test/mocks/handlers/editTrip.handler.js
  test/mocks/handlers/reset.handler.js
  test/mocks/handlers/search.handler.js
  test/mocks/handlers/tripReq.handler.js
Labels: Ready, Under Review

#25 ft Trip statistics #181414582
  package.json
  src/components/tables/TripRequests.js
  src/components/tripRequest/TripStatistics.js
  src/redux/features/statistics.features.js
  src/redux/reducers.js
  src/routes/index.js
  src/styles/index.scss
  src/views/pages/TripStatisticsView.js
  test/integration/tripStatistics.test.js
  test/jest.setup.js
  yarn.lock
Labels: Ready

#23 #181414577 Feat: Book room in accommodation
  package.json
  src/api/accomodationApi.js
  src/api/accomodationsApi.js
  src/api/index.js
  src/api/passwordApi.js
  src/api/roomApi.js
  src/assets/icons/accommodationIcon.js
  src/assets/icons/usersIcon.js
  src/components/Accommodation.js
  src/components/Accommodation/AccommodationCard.js
  src/components/Accommodation/Location.js
  src/components/Accommodation/Room.js
  src/components/Accommodation/Rooms.js
  src/components/Header/landingPageHeader.js
  src/components/SideBar/MenuItem.js
  src/components/SideBar/MenuList.js
  src/components/tables/ApprovalComponent.js
  src/components/tables/shared/MoreOptions.js
  src/constants/sidebarItems.js
  src/redux/features/accommodation.feature.js
  src/redux/reducers.js
  src/redux/views/pages.js
  src/routes/index.js
  src/styles/index.scss
  src/views/pages/Destinations.js
  src/views/pages/HomeUserView.js
  test/integration/bookRoom.test.js
  test/integration/tripReqTable.test.js
  test/mocks/handlers/index.js
  test/mocks/handlers/room.handler.js
  yarn.lock
Labels: Under Review

#31 Ft Manager's confirmation dialogue
  src/assets/icons/error_FILL0_wght400_GRAD0_opsz48.svg
  src/components/reusable/ConfirmationDialogue.js
  src/components/reusable/Spinnar.js
  src/components/tables/ApprovalComponent.js
  src/styles/index.scss
  test/integration/tripApprove.test.js
  test/integration/tripReqTable.test.js
Labels: Ready

#28 fix trip statistics
  jest.config.json
  package.json
  src/api/tripReqApi.js
  src/components/Header/DashboardHeader.js
  src/components/SideBar/MenuList.js
  src/components/tables/TripRequests.js
  src/components/tripRequest/TripStatistics.js
  src/redux/actions/statistics.action.js
  src/redux/features/statistics.features.js
  src/redux/views/pages.js
  src/routes/index.js
  src/styles/index.scss
  src/views/pages/TripStatisticsView.js
  test/integration/tripStatistics.test.js
  test/mocks/handlers/tripReq.handler.js
  yarn.lock
Labels: Ready

#30 ft-implement notification pane
  src/components/Header/DashboardHeader.js
  src/components/NotificationPane.js
  src/components/ToolTip.js
  src/components/tables/ApprovalComponent.js
  src/components/tripRequest/TripStatistics.js
  src/styles/index.scss
  test/integration/dashboardHeaders.test.js
  test/integration/tripStatistics.test.js
Labels: Ready

#29 ft-delete-comment-181414591
  src/api/tripApi.js
  src/components/password/NewPassword.js
  src/components/password/ResetPassword.js
  src/components/profile/Profile.js
  src/components/tables/shared/Header.js
  src/components/trips/Accomodations.js
  src/components/trips/Comments.js
  src/components/trips/Dialog.js
  src/components/trips/Messages.js
  src/components/trips/NewCommentForm.js
  src/redux/actions/comments.action.js
  src/redux/features/tripComments.feature.js
  src/redux/reducers.js
  src/routes/index.js
  src/styles/custom.css
  src/views/pages/CommentsPage.js
Labels: Ready

#34 feat add accomodation facility #181414576
  src/api/index.js
  src/api/roomApi.js
  src/api/userApi.js
  src/api/userRoleApi.js
  src/components/Accommodation.js
  src/components/Accommodation/newAccommodation/AddAccommodation.js
  src/components/Accommodation/newAccommodation/Stepper.js
  src/components/Accommodation/newAccommodation/StepperControl.js
  src/components/Accommodation/newAccommodation/steps/AddImage.js
  src/components/Accommodation/newAccommodation/steps/AddRooms.js
  src/components/Accommodation/newAccommodation/steps/Final.js
  src/components/Accommodation/newAccommodation/steps/SelectAccommodation.js
  src/components/chat/Modal.js
  src/contexts/StepperContext.js
  src/redux/features/accommodation.feature.js
  src/styles/index.scss
  test/integration/addRoom.test.js
Labels: Ready

#37 Ft User's re-confirmation dialogue
  src/components/reusable/ConfirmationDialogue.js
  src/components/tripRequest/EditButton.js
  src/components/tripRequest/EditRequest.js
  test/integration/editTripRequest.test.js
Labels: Ready

#32 Notification for posted comment
  package.json
  src/api/tripApi.js
  src/components/NotificationPane.js
  src/redux/features/notification.feature.js
  src/redux/reducers.js
  src/styles/index.scss
  tailwind.config.js
  test/integration/notificationPane.test.js
  yarn.lock
Labels: Ready

#36 fix:user-profile-page-view
  src/components/Header/DashboardHeader.js
  src/components/SideBar/MenuItem.js
  src/components/profile/Profile.js
  src/redux/actions/profile.action.js
  src/redux/features/accommodation.feature.js
  src/redux/features/profile.feature.js
  src/routes/index.js
  src/styles/custom.css
  src/styles/index.scss
  test/profile.test.js
Labels: Ready

#39 fix chat ui
  package.json
  src/components/chat/Messages.js
  src/components/chat/Modal.js
  src/constants/reqColumns.js
  yarn.lock
Labels: Ready
